apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: rag-build-orchestrator-
  namespace: rag-pipelines
spec:
  pipelineRef:
    name: rag-build
  params:
    - name: REPO_URL
      value: https://github.com/liqlee/avago-rag-project.git
    - name: REVISION
      value: main
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/rag-app/rag-orchestrator:latest
    - name: CONTEXT_DIR
      value: services/orchestrator
    - name: DEPLOYMENT_NAME
      value: rag-orchestrator
    - name: DEPLOYMENT_NAMESPACE
      value: rag-app
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  taskRunTemplate:
    serviceAccountName: pipeline
