FROM docker.io/library/golang:1.24 AS builder

RUN git clone --depth 1 --branch RELEASE.2025-10-15T17-29-55Z https://github.com/minio/minio.git /build/minio
WORKDIR /build/minio
RUN go build -o /usr/local/bin/minio .

FROM registry.access.redhat.com/ubi9/ubi-minimal

COPY --from=builder /usr/local/bin/minio /usr/local/bin/minio

RUN mkdir -p /data && chown 1001:0 /data

USER 1001

EXPOSE 9000 9001

ENTRYPOINT ["minio"]
